name:                megaparsecsample
version:             0.1.0.0
github:              "githubuser/megaparsecsample"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/megaparsecsample#readme>

dependencies:
- base >= 4.7 && < 5
- text == 1.2.4.1
- filepath == 1.4.2.1
- megaparsec == 8.0.0
- llvm-hs-pure == 9.0.0
- llvm-hs-pretty == 0.6.2.0
- mtl

library:
  source-dirs: src
  generated-exposed-modules:
  - Paths_megaparsecsample
  exporsed-modules:
  - Compiler
  - Interpreter
  - Parser
  - AST.hs

executables:
  megaparsecsample:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - megaparsecsample

tests:
  megaparsecsample-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - megaparsecsample
